In [1]:
# select * from table where text like '%internet%'

# What’s the internet usage policy?

# Step 1: Define Sample Documents
documents = [
    {"doc_id": "1", "section": "Pay Policies", "content": "Employees are paid bi-weekly via direct deposit."},
    {"section": "Leave of Absence", "content": "Employees must submit a leave request for approval."},
    {"section": "Internet Use", "content": "Company internet must be used for work-related tasks only."},
    {"section": "Internet Use", "content": "Company internet is a broadband internet."},
    {"section": "Break at Work", "content": "Employees can take an hour break."},
    {"section": "Harassment", "content": "Interact with each employee with Respect"}
]

# "What’s the internet usage policy?"

# No text comparison - Only Vector/ Embeddings comparison

# ([0.12655601, 0.09747529, 0.44755298, 0.11316206, 0.04429515],

# 0.12655601 - Query Vector is 12% similar to document 1's vector - Query is 12% similar to document 1

# Step 2: Get Content Texts
content_corpus = [doc["content"] for doc in documents]
content_corpus

['Employees are paid bi-weekly via direct deposit.',
 'Employees must submit a leave request for approval.',
 'Company internet must be used for work-related tasks only.',
 'Company internet is a broadband internet.',
 'Employees can take an hour break.',
 'Interact with each employee with Respect']

In [3]:
%pip install sentence-transformers


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
doc_vectors = model.encode(content_corpus)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\Alban Ssonko\Training\10_2025_GEN_AI_TRAINING\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Alban Ssonko\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [6]:
# Step 3: User Query and Semantic Matching
import numpy as np

query = "What’s the internet usage policy?"
query_vec = model.encode([query])[0]
query_vec

array([ 2.39818031e-03, -4.11839411e-02, -2.52491161e-02, -4.67050001e-02,
        4.32104338e-03,  1.65876430e-02,  1.20891683e-01, -3.50353122e-02,
        2.16832268e-03, -1.62887140e-04,  2.62876078e-02,  9.05027986e-02,
       -2.66066231e-02, -1.82131641e-02,  3.06277610e-02,  1.67854838e-02,
        1.55614000e-02, -8.26498121e-02, -3.40456739e-02, -3.08671407e-02,
        7.89995193e-02, -3.16903926e-02,  1.35831097e-02,  9.12265503e-04,
       -1.05809662e-02,  3.91191207e-02, -3.48707996e-02,  8.63874011e-05,
       -3.52702700e-02,  3.56902704e-02,  9.55277681e-03, -3.57899144e-02,
        4.84952936e-03, -4.10226583e-02, -7.66861662e-02, -1.00646779e-01,
       -9.23561007e-02, -2.47277902e-03, -2.74320990e-02,  2.85045635e-02,
        2.86295749e-02, -7.78359249e-02, -2.46461621e-03,  9.98250917e-02,
        5.86107038e-02,  2.24836301e-02,  1.56609909e-04,  1.44218523e-02,
        5.55957435e-04,  3.22429575e-02,  1.03300013e-01,  3.42919417e-02,
        3.94683518e-02,  

In [7]:
similarities = model.similarity(query_vec, doc_vectors)

# Ensure it's a 1D numpy array
similarities = np.asarray(similarities).squeeze()
similarities

array([0.12655619, 0.09747535, 0.44755295, 0.47982496, 0.11316208,
       0.04429512], dtype=float32)

In [8]:
# Now get top 3
top_3_indices = np.argsort(similarities)[::-1][:3]
print(top_3_indices)
top_scores = similarities[top_3_indices]
top_scores

[3 2 0]


array([0.47982496, 0.44755295, 0.12655619], dtype=float32)

In [9]:
top_scores

array([0.47982496, 0.44755295, 0.12655619], dtype=float32)

In [13]:
top_docs = [documents[i]['content'] for i in top_3_indices]
# documents = [
#     {"section": "Pay Policies", "content": "Employees are paid bi-weekly via direct deposit."},
#     {"section": "Leave of Absence", "content": "Employees must submit a leave request for approval."},
#     {"section": "Internet Use", "content": "Company internet must be used for work-related tasks only."},
#     {"section": "Break at Work", "content": "Employees can take an hour break."},
#     {"section": "Harassment", "content": "Interact with each employee with Respect"}
# ]

print (top_docs)
context = "\n---\n".join(top_docs)
context

['Company internet is a broadband internet.', 'Company internet must be used for work-related tasks only.', 'Employees are paid bi-weekly via direct deposit.']


'Company internet is a broadband internet.\n---\nCompany internet must be used for work-related tasks only.\n---\nEmployees are paid bi-weekly via direct deposit.'

In [14]:
import os
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv(override=True, dotenv_path="../.env")
my_api_key = os.getenv("OPEN_AI_API_KEY")

my_client = OpenAI(api_key=my_api_key)
# my_client

def ask_question_open_ai(prompt):

    # print(f"User asked: {prompt}")
    # my_client.chat.completions.create

    llm_response = my_client.chat.completions.create(
        model="gpt-5-nano",
        # messages=[
        #     {"role": "system", "content": "You are a helpful assistant. Answer as concisely as possible."},
        #     {"role": "user", "content": prompt}
        # ]
        messages=[
            {"role": "system", "content": '''
             You are an assistant who answers only based on the given context.
             '''},
            {"role": "user", "content": f"Context: {context}\n\n User Question: {query}"} 
        ]

    )
    return llm_response.choices[0].message.content  

In [15]:
print (query)
response = ask_question_open_ai(query)

What’s the internet usage policy?


In [16]:
print(f"User query: {query}")
print(f"Context: {context}")

print(f"\n\nOpen AI Response: {response}")

User query: What’s the internet usage policy?
Context: Company internet is a broadband internet.
---
Company internet must be used for work-related tasks only.
---
Employees are paid bi-weekly via direct deposit.


Open AI Response: From the provided context, the internet usage policy is:
- The company internet is broadband.
- It must be used for work-related tasks only.
